# Generated by Django 5.0.6 on 2024-05-18 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensekey',
            name='name',
            field=models.CharField(default='james', max_length=100),
            preserve_default=False,
        ),
    ]
